### ISSUE TITLE
Page Re-Order

### ISSUE THREAD

**Issue by aarproducoes** [linux-man/unreel#6]
Hello,
I'm having trouble reordering pages on Unreel.

I created a presentation and it has "sessions" as columns and below each column start have slides below.

I'm trying to grab 1 slide from one column and put it inserted in another column. However, when I use the move the slide command to the left, the whole column is moved. It's as if you changed the place columns.

Is there any way to only move the slide? Direct that only the slide I want to go to the next column?

NOTE: The "move slide up" or "move slide down" command in the same column works fine.

Is this a limitation or a problem in functionality?

Actual Table of Slides
----------------------------
COL A   | COL B   | COL C   | COL D
slide A1 | slide B1 | slide C1 | slide D1
slide A2 | slide B2 | slide C2 | slide D2
slide A3 | slide B3 | slide C3 | slide D3
slide A4 | slide B4 | slide C4 | slide D4

Table of Slides - after using "move slide to the left" on "slide B3"
----------------------------
COL B   | COL A   | COL C   | COL D
slide B1 | slide A1 | slide C1 | slide D1
slide B2 | slide A2 | slide C2 | slide D2
slide B3 | slide A3 | slide C3 | slide D3
slide B4 | slide A4 | slide C4 | slide D4

Table of Slides - desired when using "move slide to the left" on "slide B3"
----------------------------
COL A   | COL B   | COL C   | COL D
slide A1 | slide B1 | slide C1 | slide D1
slide A2 | slide B2 | slide C2 | slide D2
slide B3 | slide B4 | slide C3 | slide D3
slide A3 |              | slide C4 | slide D4
slide A4 |

**Comment by linux-man** [comment]
It was a choice based on reveal presentation structure. Each column is a `<section>` that encapsulates all slides within (each slide is also a `<section>`).
It would be possible but messy to move only one slide, and it's more useful to give the user the chance to move an entire column (offer 2 choices: move column and move slide would be overkill and bad to the interface, imho), specially because it's very easy to "clone" a slide: edit slide -> view "source code" -> select all, copy  and paste to a new slide at the desired position. Do the same with slide attributes if necessary.

**Comment by aarproducoes** [comment]
Alright! Thanks.
The clone methods works fine.

Thanks a lot of.
Congrats for the Unreel!
Very nice.
Good job.

**Comment by linux-man** [comment]
You're welcome! Thanks for using Unreel.
