### ISSUE TITLE
Link to other slides

### ISSUE THREAD

**Issue by servitecbaires** [linux-man/unreel#7]
Hello!
I found a problem trying to make links to other slides.
In slides from the first horizontal level everything works fine.
You can jump from slide 1 to 3 with a link without issues.
When I tried to link slide 1 with slide 2.2 (it means one to the right and one a level above) the results is that slide 1 makes a funny movement and then go back to slide 1
Because my English is awful, I made html file to check it. Sadly, .reel files dont even go to the linked slide in the same row.

BTW, This app is amazing!! Tnx for this piece of work!!

[reel-linking-issue.zip](https://github.com/linux-man/unreel/files/5868788/reel-linking-issue.zip)

**Comment by linux-man** [comment]
Thank you sir! It's nice to receive an ego massage once in a while.  :smile:

Seriously, Unreel is good because it depends on reveal.js - which is GREAT! In fact it's just a GUI with some extras.

About your problem: [https://revealjs.com/links/](https://revealjs.com/links/)

How to create an internal link:
![imagem](https://user-images.githubusercontent.com/1733538/105843234-5c84ad00-5fcf-11eb-8aff-3dc0d1a41db1.png)
Because first column/row are #/0/0.
Or you can create an "id" attribute (at slide attributes):
![imagem](https://user-images.githubusercontent.com/1733538/105843773-0cf2b100-5fd0-11eb-8cf9-9eb87e460e69.png)
and use it on a link
![imagem](https://user-images.githubusercontent.com/1733538/105843933-4b886b80-5fd0-11eb-9aaa-b61d7af64614.png)
The issue I find is that once you click a link, it won't work again unless you click on another internal link. Maybe it's an HTML limitation. I don't know.

Please try it.
