### ISSUE TITLE
Line Spacing Options

### ISSUE THREAD

**Issue by servitecbaires** [linux-man/unreel#8]
Hello!
I wonder if is it possible to add a line spacing button in the slide editor bar or in the slide attributes window.
When I make a table or a breakline, the line spacing is too high. In the table, the space between the cell border an the the (or any other element you put in it) is really big, no matter if you try to set the padding, spacing or height in the "Table properties" window.
Also trying to resize the whole table dragging the corners, it won't be smaller.

Thanks for your time and for bring us this amazing piece of software.
Keep taking care of your health.
Greetings from Argentina.
Marto.

**Comment by linux-man** [comment]
I don't think that a line spacing button would solve all your problems, just because HTML+CSS are a messy text formatting tool and line height don't work alone. You can't expect the level of precision you find on a document editor.
Having said that, you can do "almost" anything you want, but please, let's move to code. Try this:
At the initial presentation, first slide, edit it and open Source Code.
Change the second line to 
```html
<h1 style="margin: 0; padding: 0; line-height: 10px;">unreel</h1>
```
Tables are even worse! One advice from a web designer: export your presentation to HTML, open it on a browser, turn on Developer Tools and find what elements/properties are using that space.
Of course, this also happens because reveal.js uses "sane defaults" that don't work for you. :disappointed: 

There's a reason for that slide:
![imagem](https://user-images.githubusercontent.com/1733538/107690456-0b98d800-6ca2-11eb-8177-c002003ab381.png)
:smile:

**Comment by servitecbaires** [comment]
Thanks for your reply! I was hoping that TinyMCE could do the trick. 
Now that you told me, I can realize that the TinyMCE editor is just a HTML markup tool (yet powerful) which can be implemented with buttons.
I will rely on CSS in-line styling
